# Start with a VNC service with a new dedicated Docker image
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: ./gradlew install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080
    onOpen: open-preview
